### ISSUE TITLE
You spelt the name of the class wrong

### ISSUE THREAD

**Issue by Warren-Byron** [paulcpk/freqtrade-strategies-that-work#1]
Hi

FYI

This caught me out a bit.  You spelt the name of the class wrong:

list-strategies returns:

+-------------------------------+-----------------------------------+----------+
|                          name |                          location |   status |
|-------------------------------+-----------------------------------+----------|
| EMAPriceCrossoverWithTreshold | EMAPriceCrossoverWithThreshold.py |       OK |
+-------------------------------+-----------------------------------+----------+

Note the spelling difference between the name and the file location

Line 8:

class EMAPriceCrossoverWithTreshold(IStrategy):

Spelling should be Threshold

That causes an issue for the user trying to run the strategy if they use the correct spelling

Kind regards

**Comment by paulcpk** [comment]
@Warren-Byron found it, fixed it. Thanks!

https://github.com/paulcpk/freqtrade-strategies-that-work/commit/1e154a2f6b9aeecbaacb7db5ed6b866603daee2c
